## I want to see if games with certain words in the title sell better in some regions vs. others


In [18]:
import pandas as pd
import altair as alt
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import NMF



In [3]:
df = pd.read_csv('../data/cleaned_data/vgchartz-2024-cleaned.csv')
df.head(2)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,has_critic_score,year
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN,1,2013.0
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03,1,2014.0


### Vectorize

In [ ]:
# word_list = []

# for index, row in df.iterrows():
#     words = row['title'].split(' ')
#     print(words + word_list)
#     print(index)
#     break

vec = CountVectorizer(stop_words='english', binary=True)

X = vec.fit_transform(df['title'])



In [17]:
X.toarray()[5]

array([0, 0, 0, ..., 0, 0, 0], shape=(21341,))

### NMF to extract certain topics

In [19]:
nmf = NMF(n_components=5, random_state=42)

W = nmf.fit_transform(X)
T = nmf.components_

In [30]:
words = vec.get_feature_names_out()
print(nmf.components_.shape)
for i, topic in enumerate(nmf.components_):
    top_indexes = topic.argsort()[-10:]
    print(top_indexes)
    print(f"topic {i} contains {[words[x] for x in top_indexes]}")


(5, 21341)
[ 4323  6185 14841   653  6047  6210 20315  5392  5073  8676]
topic 0 contains ['dark', 'fighter', 'quest', 'age', 'fantasy', 'final', 'war', 'edition', 'dragon', 'ii']
[11344  6178  8127  5392 20315  4062 19220 17377  3123 20680]
topic 1 contains ['man', 'fifa', 'heroes', 'edition', 'war', 'cup', 'tour', 'soccer', 'championship', 'world']
[  232   663 16349  3597   155  5198    76 17104 20194 16518]
topic 2 contains ['2500', 'ages', 'sega', 'collection', '2000', 'ds', '1500', 'simple', 'vol', 'series']
[ 8679 18437  6404 11434  8127 10777 15585 20376 17830 18190]
topic 3 contains ['iii', 'taisen', 'force', 'mario', 'heroes', 'lego', 'robot', 'wars', 'star', 'super']
[  591 13731 13253  5684  3597  1208  2519 20111  5392  6814]
topic 4 contains ['advance', 'pack', 'official', 'episode', 'collection', 'arcade', 'boy', 'video', 'edition', 'game']
